SW1:
     hostname: 192.168.0.11
     port: 22
     username: cisco
     password: cisco
     platform: ios
     groups:
         - switch

CSR1:
     hostname: 192.168.0.13
     username: cisco
     password: cisco
     groups:
          - yaml
     connection_options:
          netconf:
               extras:
                    allow_agent: False
                    hostkey_verify: False
                    look_for_keys: False