core:
     num_workers: 100

inventory:
     plugin: nornir.plugins.inventory.simple.SimpleInventory
     options:
         host_file: "config/hosts.yaml"
         group_file: "config/groups.yaml"
         defaults_file: "config/defaults.yaml"